### PR TITLE
Global dbus bus

### PR DESCRIPTION
**Pull request by marioortizmanero**
Apparently this PR also has [this PR's](https://github.com/SwagLyrics/SwSpotify/pull/4) commits because it hasn't been moved to master yet.

* What do you think about this implementation? It's based on [this](https://stackoverflow.com/questions/279561/what-is-the-python-equivalent-of-static-variables-inside-a-function/279597#279597), which I think is better than a `try: ... except AttributeError: ...` block because of the reasoning found in the comments of the link.

### CODE REVIEW

**Comment by marioortizmanero** [comment]
It seems that `spotify_properties` can be a "global" variable too on dbus.

**Comment by marioortizmanero** [comment]
Yup, after testing, this introduces a new bug, here's the steps to reproduce it.

1. Wrap the __main__ function around a `while True:` and add sleep(1) at the end.
2. Run `python -m SwSpotify`
3. Open 1 spotify window and play the song
4. Open another spotify window and play another different song
5. Close the first song you opened
6. This error appears because the bus wasn't refreshed to the new spotify window:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mario/Programming/SwSpotify/SwSpotify/__main__.py", line 17, in <module>
    main()
  File "/home/mario/Programming/SwSpotify/SwSpotify/__main__.py", line 8, in main
    title, artist = spotify.current()
  File "/home/mario/Programming/SwSpotify/SwSpotify/spotify.py", line 117, in current
    return get_info_linux()
  File "/home/mario/Programming/SwSpotify/SwSpotify/spotify.py", line 68, in get_info_linux
    metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")
  File "/home/mario/.local/lib/python3.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/home/mario/.local/lib/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/home/mario/.local/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

Now, this is solvable but I don't know if it's a good idea to have `session_bus`, `spotify_bus` and `spotify_properties` as globals if more errors like these pop up:

```
metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")
```

```
# Refreshes the Spotify buses
try:
    metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")
except dbus.exceptions.DBusException:
    del session_bus, spotify_bus, spotify_properties
    get_info_linux()
```

**Comment by marioortizmanero** [comment]
Should I do a new PR with only the global dbus part? It looks a bit spammy now.

**Comment by aadibajpai** [comment]
> Should I do a new PR with only the global dbus part? It looks a bit spammy now.

Well I can squash and merge that basically makes all the commits into one commit before merging

**Comment by marioortizmanero** [comment]
Okay, go ahead then.

**Comment by aadibajpai** [comment]
Merging this after I fix tests which is probably this weekend

**Comment by marioortizmanero** [comment]
Good to know! By the way, I can do the squash myself to avoid you trouble. Do you want that?

**Comment by aadibajpai** [comment]
Oh well, I was away for the weekend so this got pushed even more. Thanks for your patience!

**Comment by aadibajpai** [comment]
Alright, here we go 🎉

**Comment by aadibajpai** [comment]
@marioortizmanero I did a blanket exception catching for the Mac part, since you have a VM, do you know what error we get when Spotify is closed?

**Comment by marioortizmanero** [comment]
Sure I'll try later today and let you know.

**Pull request merged**
