### PR TITLE
Try test fixing

### PR DESCRIPTION
**Pull request by aadibajpai**

### CODE REVIEW

**Comment by marioortizmanero** [comment]
hah! I tried the same thing but I ran into errors because I didn't know you could do `mock.side_effect = DBusException`. Good job

**Comment by aadibajpai** [comment]
windows tests fixed!

**Comment by aadibajpai** [comment]
@marioortizmanero any idea how to install dbus on travis? I've fixed it for windows but I'm not on linux other than wsl and `import dbus` just works there

**Comment by marioortizmanero** [comment]
I get errors on my machine when I run pytest too. But to install DBus you can follow my project's [.travis.yml](https://github.com/marioortizmanero/spotify-music-videos/blob/master/.travis.yml). The only dependencies are GLib and DBus. Anyway I think DBus is correctly installed, it's just that the tests are failing.

**Comment by aadibajpai** [comment]
> I get errors on my machine when I run pytest too. But to install DBus you can follow my project's [.travis.yml](https://github.com/marioortizmanero/spotify-music-videos/blob/next/.travis.yml) (although it also installs other stuff). The only dependencies are GLib and DBus. Anyway I think DBus is correctly installed, it's just that the tests are failing.
> 
> But as I said, these tests don't make sense to me. For what I see, it just raises a DBusException inside artist() and expects a SpotifyNotRunning. Which isn't the case in this implementation (?)

The artist function calls the current function which raises a SpotifyClosed when there's a dbus exception which should be caught by a SpotifyNotRunning since it's inherited from that.

**Comment by marioortizmanero** [comment]
No, since this update "when there's a dbus exception which should be caught by SpotifyNotRunning" is incorrect because catching the dbus exceptions isn't don't for the entire function, it's limited to the first part where you actually use it.

**Comment by aadibajpai** [comment]
Okay stuff works.

**Pull request merged**
